# Generated by Django 4.1.1 on 2022-11-17 16:09

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APREN_Nombre', models.CharField(max_length=50)),
                ('APREN_Apellido', models.CharField(max_length=50)),
                ('APREN_Documento', models.CharField(max_length=50)),
                ('APREN_Tipo_Documento', models.CharField(max_length=50)),
                ('APREN_Celular', models.CharField(max_length=50)),
                ('APREN_Estado', models.CharField(max_length=50)),
                ('APREN_Correo', models.CharField(max_length=50)),
                ('APREN_Foto', models.ImageField(blank=True, null=True, upload_to='Aprendiz/')),
            ],
            options={
                'db_table': 'Aprendiz',
            },
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CENTR_Nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Centro',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEPAR_Nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Departamento_Curso',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPRE_Tipo_Identificacion', models.CharField(max_length=50)),
                ('EMPRE_Nombre', models.CharField(max_length=50)),
                ('EMPRE_Identificacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Importar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importar', models.FileField(blank=True, null=True, upload_to='Importar/')),
            ],
            options={
                'db_table': 'Importar',
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JORNA_Nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Jornada',
            },
        ),
        migrations.CreateModel(
            name='PaisCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAISC_Nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Pais_Curso',
            },
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REGIO_Nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Regional',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SECTO_Nombre', models.CharField(max_length=50)),
                ('SECTO_NombreNuevo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Sector',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='User/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROGR_Nombre', models.CharField(max_length=50)),
                ('PROGR_Modalidad', models.CharField(max_length=50)),
                ('PROGR_Tipo_Formacion', models.CharField(max_length=50)),
                ('PROGR_Duracion', models.CharField(max_length=50)),
                ('PROGR_Version', models.CharField(max_length=50)),
                ('PROGR_Nivel', models.CharField(max_length=50)),
                ('PROGR_URL', models.FileField(blank=True, null=True, upload_to='ProgramaFor/')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.sector')),
            ],
            options={
                'db_table': 'Programa_Formacion',
            },
        ),
        migrations.CreateModel(
            name='ProgramaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROGE_Nombre', models.CharField(max_length=50)),
                ('PROGE_Modalidad', models.CharField(max_length=50)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.sector')),
            ],
            options={
                'db_table': 'Programa_Especial',
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OCUPA_Nombre', models.CharField(max_length=50)),
                ('OCUPA_Codigo_Hora', models.CharField(max_length=50)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.sector')),
            ],
            options={
                'db_table': 'Ocupacion',
            },
        ),
        migrations.CreateModel(
            name='MunicipioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MUNIC_Nombre', models.CharField(max_length=50)),
                ('departamentocurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.departamentocurso')),
            ],
            options={
                'db_table': 'Municipio_Curso',
            },
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HORAS_Monitores', models.CharField(max_length=50)),
                ('HORAS_Inst_Empresa', models.CharField(max_length=50)),
                ('HORAS_Contratista_Externos', models.CharField(max_length=50)),
                ('HORAS_Planta', models.CharField(max_length=50)),
                ('HORAS_Total', models.CharField(max_length=50)),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.ocupacion')),
            ],
            options={
                'db_table': 'Horas',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FICHA_Identificador_Unico', models.CharField(max_length=50)),
                ('FICHA_Fecha_Inicio', models.DateField()),
                ('FICHA_Fecha_Terminacion', models.DateField()),
                ('FICHA_Etapa', models.CharField(max_length=50)),
                ('FICHA_Nombre_Responsable', models.CharField(max_length=50)),
                ('FICHA_Actualizacion_Carga', models.DateField()),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.centro')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.jornada')),
                ('programaformacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.programaformacion')),
            ],
            options={
                'db_table': 'Ficha',
            },
        ),
        migrations.AddField(
            model_name='departamentocurso',
            name='paiscurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.paiscurso'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CURSO_Numero', models.CharField(max_length=50)),
                ('CURSO_Nombre', models.CharField(max_length=50)),
                ('CURSO_Estado', models.CharField(max_length=50)),
                ('CURSO_Tipo', models.CharField(max_length=50)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.jornada')),
                ('municipiocurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.municipiocurso')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.sector')),
            ],
            options={
                'db_table': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONVE_Nombre', models.CharField(max_length=50)),
                ('CONVE_Ampliacion_Cobertura', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.empresa')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.sector')),
            ],
            options={
                'db_table': 'Convenio',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONT_Fecha_Creacion', models.DateField()),
                ('CONT_Fecha_Inicio', models.DateField()),
                ('CONT_Fecha_Terminacion', models.DateField()),
                ('CONT_Estado_Aprendiz', models.CharField(max_length=50)),
                ('CONT_Estado_Contrato', models.CharField(max_length=50)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.aprendiz')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.empresa')),
            ],
            options={
                'db_table': 'Contrato',
            },
        ),
        migrations.AddField(
            model_name='centro',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.regional'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSennova.ficha'),
        ),
    ]
