# Generated by Django 4.1.1 on 2022-11-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSennova', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Instructor'), (2, 'Administrador')], null=True),
        ),
    ]
