# Generated by Django 4.1.1 on 2022-12-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSennova', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='EMPRE_Identificacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, default='User/user.jpg', null=True, upload_to='User/'),
        ),
    ]
