# Generated by Django 4.1.1 on 2022-12-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSennova', '0003_alter_empresa_empre_identificacion_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='APREN_Celular',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='APREN_Documento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='CURSO_Numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='FICHA_Identificador_Unico',
            field=models.IntegerField(),
        ),
    ]
